sudo: required

language: generic 

services:
  - docker

before_install:
  - docker build -t kyruel/docker-react -f dockerfile.dev . 

script:
  - docker run -e CI=true kyruel/docker-react npm run test